blog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('BlogPost')

blog/blog_posts/views.py
import sys
from flask import render_template,url_for,flash, redirect,request,Blueprint,abort
from flask_login import current_user,login_required
from flask_migrate import current
from blog import db
from blog.models import BlogPost
from blog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                             text=form.text.data,
                             user_name=current_user.username
                             )
        db.session.add(blog_post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


# Blog Post (View)
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title,
                            date=blog_post.date, post=blog_post)


# Update
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET', 'POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.user_name != current_user.username:
        abort(403)
    
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash("Blog Post Updated")
        return redirect(url_for('core.index'))
    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title='Update', form=form)


# Delete
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.user_name != current_user.username:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted')
    return redirect(url_for('core.index'))

blog/core/views.py
from flask import render_template,request,Blueprint
from blog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def info():
    return render_template('info.html')

@core.route('/blog_posts')
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('index.html',blog_posts=blog_posts)

blog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blog import db
from werkzeug.security import generate_password_hash,check_password_hash
from blog.models import User, BlogPost
from blog.users.forms import RegisterForm, LoginForm


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Logged in successfully.')
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.info')
            return redirect(next)
    return render_template('login.html', form=form)

@users.route("/logout")
def logout():
    logout_user()
    flash("You have been logged out!", category='info')
    return redirect(url_for('core.info'))

@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(id=current_user.id).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user, username=username)

blog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('core.info') }}">Flask-blog</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link text-nowrap" href="{{ url_for('core.index') }}">Blog Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-nowrap" href="{{ url_for('users.user_posts', username=current_user.username) }}">My Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-nowrap" href="{{ url_for('blog_posts.create_post') }}">Create Post</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-nowrap" href="{{ url_for('core.index') }}">Blog Posts</a>
          </li>    
          {% endif %}
        </ul>
      </div>

      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
          {% if not current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.login') }}">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a>
            </li>
          {% endif %}
        </ul>
      </div>  
    </nav>
<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

blog/templates/blog_post.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <div>Written by: {{post.user_name}}</div>
  <div>Published: {{ post.date.strftime('%B %d, %Y') }}</div>
  <br>
  <p><em>{{post.text}}</em></p>
   {% if post.id == current_user.id %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>

  <!-- Modal for Pop Up-->
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

blog/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST">
     {{ form.hidden_tag() }}

     <br>
     <br>
     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info", placeholder="Post") }}
     </div>
  </form>

</div>

{% endblock content %}

blog/templates/index.html
{% extends "base.html" %}
{% block content %}
    <br>
    <div class="jumbotron">
        <h1>Blog Posts</h1>
    </div>

    <div class="container">
        {% for post in blog_posts.items %}
            <div class="card">
                <div class="card-body">
                    <h2><a class="card-title" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
                    <br>
                    <div> Written by: {{ post.user_name }}</div>
                    <p>Published on: {{ post.date.strftime('%B %d, %Y') }}</p>
                    <a class="btn btn-primary" href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">Read Blog Post</a>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                  {% if blog_posts.page == page_num %}
                    <li class="page-item disabled">
                        <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
                    </li>
                  {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a>
                    </li>
                  {% endif %}
          {% endfor %}
      </nav>
{% endblock %}

blog/templates/info.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<div class="jumbotron">
  <h1>About our website</h1>
  <br>
  <p>If you want to share anything, or read posts written by others, you've come to right place :)<br>
    You can create posts when you are logged in. Registration and postings are totally free !</p>
</div>

{% endblock %}

blog/templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    <br>
    <br>
    <h1 class="h3 mb-3 font-weight-normal">
        Please Sign in
    </h1>
    <br>
    {{ form.hidden_tag() }}
    {{ form.username(class="form-control", placeholder="User Name") }}
    {{ form.password(class="form-control", placeholder="Password") }}<br>
    {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
    <br>
    <div class="checkbox mb-3">
        <h6>You don't have an account?</h6>
        <a class="btn btn-sm btn-secondary" href="{{ url_for('users.register') }}">Register</a>
    </div>   
</form>
{% endblock %}

blog/templates/register.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
            {{ form.hidden_tag() }}
            <br>
            <br>
            <h1 class="h3 mb-3 font-weight-normal">
                Please Create your Account
            </h1>
            <br>
            {{ form.hidden_tag() }}
            {{ form.email(class="form-control", placeholder="Email") }}
            {{ form.username(class="form-control", placeholder="User Name") }}
            {{ form.password(class="form-control", placeholder="Password") }}
            {{ form.pass_confirm(class="form-control", placeholder="Confirm password") }}
            <br>
            {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
            <br>
            <div class="checkbox mb-3">
               <h6>Already have an account?</h6>
               <a class="btn btn-sm btn-secondary" href="{{ url_for('users.login') }}">Sign in</a>
            </div>           

    </form>
{% endblock %}

blog/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <br>
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
    </div>
  </div>


{% for post in blog_posts.items %}
          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          <br>
          <div>Written by: {{ username }}</div>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <p><em>{{post.text}}</em></p>
          <br>
{% endfor %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
              </li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}